# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'
inhibit_all_warnings!

target 'JMImgure' do

pod 'SDWebImage'
pod 'AFNetworking'

end

target 'JMImgure Share' do

pod 'SDWebImage'
pod 'AFNetworking'

end
